name: dev-apply

on:
  push:
    branches:
      - master

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo Setup

  terraform-prod:
    name: Terraform-Prod
    runs-on: ubuntu-latest
    needs: Setup

    defaults:
      run:
        shell: bash
        working-directory: "./src/prod"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
