name: "Terraform plan"
on:
  push:
    branches:
      - dev
  pull_request:
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tfnotify
        id: install
        run: |
          sudo curl -fL -o tfnotify.tar.gz https://github.com/mercari/tfnotify/releases/download/v0.7.0/tfnotify_linux_amd64.tar.gz
          sudo tar -C /usr/bin -xzf ./tfnotify.tar.gz

      - name: Terraform Plan
        id: plan
        run: terraform plan | tfnotify -config .tfnotify/github.yaml plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
