name: pr-plan

on:
  push:
    branches-ignore:
      - develop
      - master
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo Setup

  terraform-dev:
    name: Show Terraform Dev difference
    runs-on: ubuntu-latest
    needs: Setup

    defaults:
      run:
        shell: bash
        working-directory: "./src/dev"

    steps:
      - uses: actions/checkout@v2
      - name: notify-Terraform-init-plan
        uses: actions/tfnotify-composite-action@v1.0.1

  terraform-prod:
    name: Show Terraform Prod difference
    runs-on: ubuntu-latest
    needs: Setup

    defaults:
      run:
        shell: bash
        working-directory: "./src/prod"

    steps:
      - uses: actions/checkout@v2
      - name: notify-Terraform-init-plan
        uses: actions/tfnotify-composite-action@v1.0.1
