name: pr-plan

on:
  push:
    branches-ignore:
      - develop
      - master
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo Setup

  terraform-dev:
    name: Show Terraform Dev difference
    runs-on: ubuntu-latest
    needs: Setup

    defaults:
      run:
        shell: bash
        working-directory: "./src/dev"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # comement
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - uses: actions/checkout@v2
      - name: notify-Terraform-init-plan
        uses: comu2e/tfnotify-composite-action@1.0.2

  terraform-prod:
    name: Show Terraform Prod difference
    runs-on: ubuntu-latest
    needs: Setup

    defaults:
      run:
        shell: bash
        working-directory: "./src/prod"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # comement
      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - uses: actions/checkout@v2
      - name: notify-Terraform-init-plan
        uses: comu2e/tfnotify-composite-action@1.0.2
